### ISSUE TITLE
More simplified UX

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#102]
A common scenario is to get content such as manifest and blob into the memory for further processing.

Although the `Resolve()` and `Fetch()` methods in the `Target` interface provides a simple clean secure way to read content, we still need a simplier UX such as `GetManifest()` and `GetBlob()` (or can be further combined as `GetContent()`). Similarly, we might also need `PutContent()` in the `oras` package.

**Comment by sajayantony** [comment]
We should start discussing an RC bar at this point and once that is release update notation, ratify and other projects like oras CLI.

**Comment by shizhMSFT** [comment]
An interesting user case can be found at #22

**Comment by Wwwsylvia** [comment]
This one might be useful - https://github.com/oras-project/oras-go/pull/182#discussion_r899787777

**Comment by Wwwsylvia** [comment]
Based on the [discussion](#240), I will break down this issue into several sub-tasks and will send PRs separately. 

- [ ] Utility method for getting content
- [ ] Utility method for putting content
- [ ] Utility method for specifying static credentials
- [ ] Utility methods for manipulating descriptors

**Comment by Wwwsylvia** [comment]
Closing as all sub-tasks are done.
