### ISSUE TITLE
Support for the oci content store in v1?

### ISSUE THREAD

**Issue by viovanov** [oras-project/oras-go#113]
Hi! Is there planned support in v1 for local OCI content stores?
We've been using it in https://github.com/opcr-io/policy - version 0.4.0.

**Comment by shizhMSFT** [comment]
@viovanov `v1` depends on `containerd`. Thus you can use the [containerd OCI content store implementation](https://github.com/containerd/containerd/blob/main/content/local/store.go#L72) directly.

**Comment by shizhMSFT** [comment]
@viovanov Currently, we don't have plan to implement new features for `v1`. 

> The [v1](https://github.com/oras-project/oras-go/tree/v1) branch is maintained for API stability, dependency updates, and security patches.

Please try `v2` instead and help us make `v2` better by sharing experiences and open issues.

**Comment by shizhMSFT** [comment]
Closing as `v2` is suggested. Please re-open if there is an update.
