### ISSUE TITLE
Add retag function for TagResolver interface

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-go#120]
As a developer, I want oras go to have `Retag` function so I rename a tag. Function signature would be like
```
ReTag(ctx context.Context, oldReference string, newReference string) error

**Comment by Wwwsylvia** [comment]
Make sense.
It can be `func Tag(ctx context.Context, repo Repository, srcRef, dstRef string) error` in the package `registry`. And we can have it leverage the `FetchReference` and `PushReference` functions to minimize the number of calls.

**Comment by shizhMSFT** [comment]
@patrickzheng200 Could you help with this?

**Comment by patrickzheng200** [comment]
> @patrickzheng200 Could you help with this?

Taking a look.
