### ISSUE TITLE
Repository level auth provider support

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#136]
The `auth.Client` takes a `Credential` function which accepts a registry string.

https://github.com/oras-project/oras-go/blob/ed1a2571617eca7b6661df33038a0910fdbe15f6/registry/remote/auth/client.go#L71

Instead of just a registry host, the `Credential` function should take a `Reference` object to achieve repository level auth if hinted in the request context. If the `Reference` object is not hinted, a `Reference` object is created where the `Registry` field is the request host.

**Comment by shizhMSFT** [comment]
In addition to the functionality, I also have the following security considerations:

- The hinted reference registry should match the registry host in the request to avoid sending the credentials to random parties.

**Comment by shizhMSFT** [comment]
There are also problems with repository levels, such as
- Catalog list
- Blob mount across repositories

**Comment by FeynmanZhou** [comment]
It looks like a multi-tenancy scenario. It depends on whether the ORAS has the fine-grained authentication requirement. Maybe we can remain this issue open and wait for more feedback. 

cc @SteveLasker @sajayantony

**Comment by shizhMSFT** [comment]
Closing as repository level auth provider might not be a real requirement since we can configure `Credential` of `*auth.Client` for individual `*remote.Repository` in the real world.
