### ISSUE TITLE
Question about writerOpts in file.go

### ISSUE THREAD

**Issue by vsoch** [oras-project/oras-go#14]
Heyo! I have a very naive question about the WriterOpts here:

https://github.com/oras-project/oras-go/blob/9ee134908701608848ede3c77efbeaa568fee55f/pkg/content/file.go#L221

How can there be a Desc attribute if "Desc" isn't part of the structure here?

https://github.com/oras-project/oras-go/blob/9ee134908701608848ede3c77efbeaa568fee55f/pkg/content/opts.go#L24

Is it somehow added with the loop to update the opts, or is the field supposed to be the InputHash or OutputHash?

Thanks!

**Comment by bacongobbler** [comment]
You're looking at the wrong WriterOpts. file.go [depends on `containerd/content`](https://github.com/oras-project/oras-go/blob/9ee134908701608848ede3c77efbeaa568fee55f/pkg/content/file.go#L29) which defines a `Desc` field. See https://pkg.go.dev/github.com/containerd/containerd/content#WriterOpts.

**Comment by vsoch** [comment]
Oh dog! Should have looked at the imports! Thank you!
