### ISSUE TITLE
Implement `aritfactType` filtering

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#140]
The current [remote.Repository](https://github.com/oras-project/oras-go/blob/main/registry/remote/repository.go#L343) does not support [artifact type filtering](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md#filtering-results) for the referral API. It is marked as an to-do item.

**Comment by m5i-work** [comment]
@shizhMSFT Let me take a look.
