### ISSUE TITLE
Add examples for the auth package

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#149]
We need to add some examples for the [auth package](https://github.com/oras-project/oras-go/tree/main/registry/remote/auth), just like [example_test.go](https://github.com/oras-project/oras-go/blob/main/registry/remote/example_test.go).
This work is part of #60.

**Comment by shizhMSFT** [comment]
@wangxiaoxuan273 Could you also pick up this one?

**Comment by wangxiaoxuan273** [comment]
Please assign this to me, thanks
