### ISSUE TITLE
Update to Go 1.18

### ISSUE THREAD

**Issue by lucacome** [oras-project/oras-go#161]
Go 1.18 was [released](https://go.dev/blog/go1.18) and brings a few improvements and bug fixes. 

I'm still not 100% familiar with the codebase, but I think some of the benefits for the project are:

> Apple M1, ARM64, and PowerPC64 users rejoice! Go 1.18 includes CPU performance improvements of up to 20% due to the expansion of Go 1.17’s register ABI calling convention to these architectures

>The linker emits [far fewer relocations](https://tailscale.com/blog/go-linker/). As a result, most codebases will link faster, require less memory to link, and generate smaller binaries. Tools that process Go binaries should use Go 1.18's debug/gosym package to transparently handle both old and new binaries.

> TLS 1.0 and 1.1 disabled by default client-side

> Rejecting SHA-1 certificates

Also until specific features for 1.18 are used (like the use of generics) it will still be possible to compile with go 1.17

**Comment by shizhMSFT** [comment]
As mentioned in #153, the version in the `go.mod` is the minimum version. `go 1.17` simply means that the `oras-go` library can be compiled against go 1.17, 1.18, and newer versions.

**Comment by shizhMSFT** [comment]
Closing as this issue is succeeded by #261
