### ISSUE TITLE
creation of a new ORAS Artifact manifest should set `io.cncf.oras.artifact.created`

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras-go#175]
ORAS Artifact manifests added `io.cncf.oras.artifact.created` to account for artifact lifecycle management as an artifact is promoted across registries. See [ORAS Artifact Manifest Properties](https://github.com/oras-project/artifacts-spec/blob/main/artifact-manifest.md#oras-artifact-manifest-properties) and the [Referrers Sorting Results API](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md#sorting-results)

To assure all new artifacts have a `io.cncf.oras.artifact.created` value, `oras-go` should set it on manifest creation. If a user provides the value, we should accept their value, be we should have a default.

Setting the `created` annotation enables scenarios for pulling a collection of reference types, that may overlay the same information.
- I may pull a collection of scan reports for the `net-monitor:v1` image. How do I sort the collection to know the last, or even the first?
- I pull a collection of annotations, that update the `eol` date for the `net-monitor:v1` image. I need the newest value to account for the latest information.

"io.cncf.oras.artifact.created": "2022-06-13T22:11:10.08Z"

**Comment by shizhMSFT** [comment]
@SteveLasker Is this annotation field `io.cncf.oras.artifact.created` a MUST or SHOULD or MAY?

**Comment by SteveLasker** [comment]
Good question @shizhMSFT. The spec doesn't actually call out MUST, SHOULD, MAY. 
And, that is a good question to raise. From an oras-go library, setting the value will help users with smart defaults, so adding this will make the default scenarios easier to consume later.

**Comment by shizhMSFT** [comment]
@binbin-li We need to update the `notation-go` implementation once this issue is addressed.

**Comment by SteveLasker** [comment]
Woot, woot. Chipping away at the details.
