### ISSUE TITLE
Fail to push if port 443 is explicitly specified in the hostname

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#177]
If the port `443` is explicitly set to the hostname like `myregistry:443/myrepo`, blob push will fail since the hostname of the `Location` header in the response is set to `myregistry` instead of `myregistry:443`.

https://github.com/oras-project/oras-go/blob/4ed4d30e890b9ff39c8dc231f98e80637badce00/registry/remote/repository.go#L520

Thus, the auth client missed the cache and fails.

**Comment by shizhMSFT** [comment]
This bug applies to port `443` for HTTPS and port `80` for HTTP.

**Comment by shizhMSFT** [comment]
@patrickzheng200 Could you help fixing this bug?

**Comment by patrickzheng200** [comment]
Taking a look.

**Comment by shizhMSFT** [comment]
Here are the repro steps:
1. Setup a registry with basic auth and SSL. The port is open to `443` (e.g. `localhost:443`).
2. Use `oras-go` to push a blob to `localhost:443/somerepo` with credentials.

The step 2 will fail.
