### ISSUE TITLE
List images and tags

### ISSUE THREAD

**Issue by luisdavim** [oras-project/oras-go#19]
Is it possible to list images and tags from the remote repository?

EDIT: To give some more context.

I'm writing a CLI tool that supports plugins and I'm using `oras-go` to publish and install plugins to and from a docker repo where each plugin is a tag I'd like to be able to provide a list or search command that allows discovering plugins and display some information from it's annotations.

I've been looking around the `fetcher` but it seems to require that you provide a reference with a tag.

**Comment by sajayantony** [comment]
This is a fair ask and the API are covered under distribution. I think we would love to add this to the library.

**Comment by scottrigby** [comment]
This has been addressed in `main` for v2 (I believe by #57 and #58, though someone help link to the correct PRs if I'm wrong about that).

A backport for v1 is being worked on now by @sabre1041
Also see https://github.com/helm/helm/issues/9694#issuecomment-1004910307

**Comment by sabre1041** [comment]
@scottrigby Right now, the work is scoped to the tag listing. The image listing will still remain outstanding

**Comment by scottrigby** [comment]
Good point @sabre1041 

Clarification between listing images and tags, by ORAS branch (related to ORAS MAJOR version). In `main` (for forthcoming v2) you can pass in a registry and it will provide a list of repositories (images). You can also list all tags of an image.

@luisdavim At the time of your OP there was not a stable version, so assume you OK with using `main`.

The backport to v1 @sabre1041 is working on is currently scoped just to only all tags given an image, not to list all images in a registry. The reason for this current scope is this is needed in a _stable release_ of ORAS to move Helm OCI support out of experimental.

**Comment by shizhMSFT** [comment]
Closing the issue as this has been addressed in `main` and has been backported to `v1`.
