### ISSUE TITLE
Support `last` parameter for listing catalog and tags

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#196]
Users may want to start listing catalog and tag list in the middle with the `last` parameter.

Original discussion: https://cloud-native.slack.com/archives/CJ1KHJM5Z/p1655960108401079

See also:
- https://docs.docker.com/registry/spec/api/#pagination
- https://docs.docker.com/registry/spec/api/#pagination-1

**Comment by shizhMSFT** [comment]
@patrickzheng200 Could you prioritize this item?

**Comment by patrickzheng200** [comment]
> @patrickzheng200 Could you prioritize this item?

Taking a look.

**Comment by gfichtenholt** [comment]
I checked and the fix is working. Thank you very much
