### ISSUE TITLE
Support `v1.0.0-rc.1` ORAS Artifact manifest schema

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#200]
Update oras-go to support the `v1.0.0-rc.1` [ORAS Artifact manifest schema](https://github.com/oras-project/artifacts-spec/blob/v1.0.0-rc.1/artifact-manifest.md).

- [x] #221
- [x] #207
- [x] #206
- [x] #208
- [x] #202

This issue is part of #131.

**Comment by shizhMSFT** [comment]
Closing as all tasks are resolved.
