### ISSUE TITLE
Support filtering predecessors by artifact type on ExtendedCopy

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#201]
When using [ExtendedCopy](https://github.com/oras-project/oras-go/blob/main/extendedcopy.go#L62), clients may want to filter predecessors of a node by their artifact type. Specifically,

- Include predecessors whose artifact type matches a given regex
- Exclude predecessors whose artifact type matches a given regex

To support this, we can provide some utility methods that configure the [FindPredecessors](https://github.com/oras-project/oras-go/blob/main/extendedcopy.go#L54) option for clients.

Original issue: #29

**Comment by Wwwsylvia** [comment]
@wangxiaoxuan273 Could you help with this?

**Comment by wangxiaoxuan273** [comment]
Sure. Please assign this to me.

**Comment by shizhMSFT** [comment]
Scenario: https://github.com/oras-project/oras/issues/307

**Comment by wangxiaoxuan273** [comment]
There are several things we need to clarify:
1. `ArtifactType` is only supported by `remote.repository` and `Referrers()`. `ExtendedCopyOptions` only works on OCIDescriptors which does not support `ArtifactType`. Given this fact, what should be the scope of this requirement? **Should the filtering only work on `remote.repository`?** And if so, where should we check the source type?

**Comment by wangxiaoxuan273** [comment]
2. Should we support both inclusion and exclusion?
3. Should we support regex?

@shizhMSFT

**Comment by shizhMSFT** [comment]
> There are several things we need to clarify:
> 
> 1. `ArtifactType` is only supported by `remote.repository` and `Referrers()`. `ExtendedCopyOptions` only works on `OCIDescriptors` which does not support `ArtifactType`. Given this fact, what should be the scope of this requirement? **Should the filtering only work on `remote.repository`?** And if so, where should we check the source type? And what should be the functions' behavior on non-repository source?

It is clear if the Target implements `Referrers()`.

The question is how we can filter without referrer API for generic Targets. The solution is as simple as
1. Get the successors of a certain node
2. For each successor, check if it is an artifact manifest type. If so, read it and check its artifact type.

> 2. Should we support both inclusion and exclusion?
Yes. That's intersection.

> 3. Should we support regex?
Why not 😃

**Comment by shizhMSFT** [comment]
Resolved by #258
