### ISSUE TITLE
Support filtering predecessors by annotation on ExtendedCopy 

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#203]
When using [ExtendedCopy](https://github.com/oras-project/oras-go/blob/main/extendedcopy.go#L62), clients may want to filter predecessors of a node by their annotation. Specifically,

- Include predecessors whose annotation matches a given regex
- Exclude predecessors whose annotation matches a given regex

To support this, we can provide some utility methods that configure the [FindPredecessors](https://github.com/oras-project/oras-go/blob/main/extendedcopy.go#L54) option for clients.

Original issue: #29

**Comment by Wwwsylvia** [comment]
@wangxiaoxuan273 Could you help with this?

**Comment by wangxiaoxuan273** [comment]
Sure. Please assign this to me.

**Comment by shizhMSFT** [comment]
Scenario: https://github.com/oras-project/oras/issues/307

**Comment by shizhMSFT** [comment]
Resolved by #259
