### ISSUE TITLE
Support platform selection on Copy

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#210]
When using [Copy](https://github.com/oras-project/oras-go/blob/main/copy.go#L84), clients may want to select a manifest of a specific platform from a Manifest List/Manifest Index that is resolved from a reference.

To support this, we can provide some utility methods that configure the [MapRoot](https://github.com/oras-project/oras-go/blob/main/copy.go#L54) option for clients.

**Comment by lizMSFT** [comment]
assigned

**Comment by lizMSFT** [comment]
Thoughts on Support Platform Selection on Copy Func: https://github.com/oras-project/oras-go/discussions/235
