### ISSUE TITLE
Fix runnable examples

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#218]
The following runnable examples fail to run on the GoDoc website. We need to fix this as it may confuse users.

- [Registry interaction examples](https://pkg.go.dev/oras.land/oras-go/v2@main/registry#pkg-examples)
- [Repository interaction examples](https://pkg.go.dev/oras.land/oras-go/v2@main/registry/remote#pkg-examples)
- [Authentication examples](https://pkg.go.dev/oras.land/oras-go/v2@main/registry/remote/auth#pkg-examples)

To reproduce, click the `Run` button under the example.
![image](https://user-images.githubusercontent.com/8113721/176602727-708e57cc-25bb-4166-b64b-17aa56070dd8.png)

**Comment by lizMSFT** [comment]
assigned
