### ISSUE TITLE
Migrate to codecov.io

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#233]
We are currently use `go test` to generate coverage report and those reports are uploaded as GitHub artifacts. However, we don't have a method to compare coverage report from commit to commit, or even view the report easily.

I propose that we should migrate our coverage report generation to [codecov.io](https://about.codecov.io/) similar to https://github.com/veraison/go-cose/pull/84. By doing so, we can also have a badge in `README.md`.

/cc @Wwwsylvia @FeynmanZhou @yizha1

**Comment by FeynmanZhou** [comment]
Support. Codecov is useful to generate the test coverage report in each Pull Request.

**Comment by Wwwsylvia** [comment]
Looks nice!

**Comment by CharingJC** [comment]
ack
