### ISSUE TITLE
Failed to download all the files in an artifact using oras.Copy()

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-go#236]
# Repro Steps
1. Prepare two files `foo` and `bar` with same content:
```
foo bar
```
2. Pack and push an artifact with two files containing exact same content
```
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "config": {
        "mediaType": "application/vnd.unknown.config.v1+json",
        "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
        "size": 2
    },
    "layers": [
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar",
            "digest": "sha256:545c0e29a021fc393a82fb4ead2f1e68f23536f876aa34b0716b2c0eb0d3d1d4",
            "size": 20,
            "annotations": {
                "org.opencontainers.image.title": "foo"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar",
            "digest": "sha256:545c0e29a021fc393a82fb4ead2f1e68f23536f876aa34b0716b2c0eb0d3d1d4",
            "size": 20,
            "annotations": {
                "org.opencontainers.image.title": "bar"
            }
        }
    ]
}
```
3. Pull the pushed artifact to a local file store, only `foo` or `bar` will be pulled

# Root cause
When copying, oras-go will deduplicate blob uploading with `status.TryCommit`(related [code](https://github.com/oras-project/oras-go/blob/main/internal/status/tracker.go#L35-L43)). Since file `foo` and `bar` are pointing to the same layer blob, only one file download will be committed. The other one will be sliently ignored.

The deduplication works for all the target types except for file. We should have a workaround for file target.

**Comment by Wwwsylvia** [comment]
One workaround is that, when a manifest is pushed to the file store, the file store checks if all the files (named blobs) specified in the manifest are present in the file store. If a file is missing, but another blob with the same digest exists, the file store can automatically generate the missing file using the existing content.
We can expose a flag option for this behavior. Users would need to turn on this flag when using file store as the destination target of copying.
