### ISSUE TITLE
Extend platform package

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-go#246]
After merging #244, oras-go will support specifying platform in the copy option. There are still some todos on extending the package, such as:
1) Making the package public so client can reuse the platform matching code(e.g. oras-project/oras#449
2) Extend the package with all OCI manifest related matching like media type or annotation. #148

_Originally posted by @qweeah in https://github.com/oras-project/oras-go/pull/244#discussion_r925225458_

**Comment by shizhMSFT** [comment]
Is there any reason to make the `platform` package public?

**Comment by qweeah** [comment]
> Is there any reason to make the `platform` package public?

Yes, for fetching manifests, ORAS CLI can reuse platform.Match

**Comment by shizhMSFT** [comment]
Closed as comments are outdated.
