### ISSUE TITLE
Shift Go Support Window to [1.18, 1.19]

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#261]
[Go 1.19](https://go.dev/blog/go1.19) is released with [release notes](https://go.dev/doc/go1.19)!

It is time to shift the window for go support to `[1.18, 1.19]` by updating

- `go. mod`
- GitHub Actions

Although we will set `1.18` as the minimum version of `oras-go`, it is still possible to compile `oras-go` with go 1.17.

**Comment by wangxiaoxuan273** [comment]
Please assign this to me.
