### ISSUE TITLE
`FilterAnnotation` in `ExtendedCopy` does not work as expected

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#265]
The `FilterAnnotation` in `ExtendedCopy` relies on the `Predecessor()`, which may be implemented by `Referrers()`. However, those APIs does not return annotations as expected and thus filter annotation will always fail.

**Comment by shizhMSFT** [comment]
@wangxiaoxuan273 Could you take a look and catch the release train?

/cc @Wwwsylvia

**Comment by wangxiaoxuan273** [comment]
Sure. Will fix it tomorrow.
