### ISSUE TITLE
Support OCI Artifacts and reference types

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras-go#267]
As the reference type working group has submitted the PR to OCI, https://github.com/opencontainers/image-spec/pull/934 and https://github.com/opencontainers/distribution-spec/pull/335 ORAS needs to support the implementation of these media types and APIs

_This issue does not track the updates/changes to ORAS artifacts or API due to the above and should only focus on making sure that the ORAS project ensures that it implements the OCI specification._

**Comment by sajayantony** [comment]
Both PRs are not merged and OCI has an release candidate. 
Oras should be able to consume the specification and fully unblocked - 

https://github.com/opencontainers/image-spec/tree/v1.1.0-rc1
https://github.com/opencontainers/distribution-spec/tree/v1.1.0-rc1

**Comment by shizhMSFT** [comment]
Closed by #271
