### ISSUE TITLE
Support OCI Artifacts and referrers API

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras-go#268]
As the reference type working group has submitted the PR to OCI, https://github.com/opencontainers/image-spec/pull/934 and https://github.com/opencontainers/distribution-spec/pull/335 ORAS needs to support the implementation of these media types and APIs

This is dependent on - https://github.com/oras-project/oras-go/issues/267

_This issue does not track the issue for change/updates of ORAS artifacts or API and should only focus on making sure that the ORAS project ensures that it implements the OCI specification._

**Comment by shizhMSFT** [comment]
Closed by #271
