### ISSUE TITLE
How to use token access acr without login in `v2.0.0`

### ISSUE THREAD

**Issue by ninjadq** [oras-project/oras-go#269]
Hi team,

In our scenario, we leverage MSI to fetch the access token and use that token to push artifacts or images to ACR without login.

The code is like this in `v1.2.0`

```go
...
opts := content.RegistryOptions{
		Username: "00000000-0000-0000-0000-000000000000",
		Password: token,
}

...

registry, err := content.NewRegistry(opts)

...

oras.Copy(ctx, fileStore, ref, registry, "")
```

But currently in `v2.0.0` there is no place to put username and password for registry.

Anyone knows how to handle this with `v2.0.0`

Thanks

**Comment by FeynmanZhou** [comment]
I hope [this example](https://pkg.go.dev/oras.land/oras-go/v2@main/registry/remote/auth#Credential) can help you.

Hi @Wwwsylvia @wangxiaoxuan273 , could you pls help to take a look?

**Comment by shizhMSFT** [comment]
@ninjadq Please refer [this example](https://pkg.go.dev/oras.land/oras-go/v2@main/registry/remote/auth#example-Client.Do-WithRefreshToken) to construct an `*auth.Client` where `RefreshToken` is set to the `token` obtained from MSI.

Later, you can do something like

```golang
repo, err := remote.NewRepository(repoName)
if err != nil {
	panic(err)
}
repo.Client = configuredAuthClient
```

**Comment by wangxiaoxuan273** [comment]
@ninjadq For registry, do something like this:
The Username and Password fields of auth.Credential can be replaced with AccessToken or RefreshToken fields, depending on the details of MSI credentials. Please refer to the [examples](https://pkg.go.dev/oras.land/oras-go/v2@main/registry/remote/auth#example-Client.Do-BasicAuth) of configuring the client.

```
reg, err := remote.NewRegistry("example.azurecr.io")
	if err != nil {
		return err
	}
	reg.Client = &auth.Client{
		Client: &http.Client{
			Transport: NewTransport(http.DefaultTransport),
		},
		Credential: func(ctx context.Context, reg string) (auth.Credential, error) {
			if reg == "example.azurecr.io" {
				return auth.Credential{
					Username: username,
					Password: token,
				}, nil
			}
			return auth.EmptyCredential, nil
		},
		Cache: auth.DefaultCache,
	}
	repo, _ := reg.Repository(ctx, "repo1")
```

**Comment by ninjadq** [comment]
Thank you for your detailed explanation @wangxiaoxuan273 @shizhMSFT
