### ISSUE TITLE
Migrate to OCI Artifact from ORAS Artifact

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#271]
We will migrate to OCI Artifact from ORAS Artifact once the following PRs are merged.

- https://github.com/opencontainers/image-spec/pull/934
- https://github.com/opencontainers/distribution-spec/pull/335

Tasks:

- [x] #307
- [x] #308
- [x] #309
- [x] #310
- [x] #311
- [x] #312
- [x] #347 

This issue covers #267 and #268.

**Comment by sajayantony** [comment]
Should we start a new branch for OCI now that you have go structs for OCI. Similarly, for oras - CLI?

**Comment by rdpsin** [comment]
Any update on this work?

**Comment by Wwwsylvia** [comment]
@rdpsin We will be working on this after releasing `oras-go` `v2.0.0-rc3`, which is scheduled for Sep. 5th.

**Comment by SteveLasker** [comment]
Just a clarification that we'll need to maintain support for ORAS artifacts, until all registries have migrated to the OCI Artifact spec.
1. Check if `/referrers` is supported (best future case)
2. Check if `_oras/referrers` is supported (limited time, as ACR, ECR and Zot migrate to `/referrers`)
3. Fallback to using OCI Image manifest, with a `refers/subject` property (see [Rename refers field to subject #950](https://github.com/opencontainers/image-spec/pull/950))

**Comment by shizhMSFT** [comment]
> Just a clarification that we'll need to maintain support for ORAS artifacts, until all registries have migrated to the OCI Artifact spec.
> 
> 1. Check if `/referrers` is supported (best future case)
> 2. Check if `_oras/referrers` is supported (limited time, as ACR, ECR and Zot migrate to `/referrers`)
> 3. Fallback to using OCI Image manifest, with a `refers/subject` property (see [Rename refers field to subject #950](https://github.com/opencontainers/image-spec/pull/950))

The initial iteration will not have the fallback to ORAS Artifact referrers. The fallback will be added in the second iteration after proper discussions.

**Comment by sajayantony** [comment]
Oras needs to consume RC2 since it includes the subject field - https://github.com/opencontainers/image-spec/pull/958

**Comment by michaelb990** [comment]
> The fallback will be added in the second iteration after proper discussions.

What fallback are we talking about here? From what I read, it seemed like falling back to ORAS Artifacts wouldn't be compatible with the tag-based fallback already proposed in the OCI distribution-spec, now an RC.

**Comment by sajayantony** [comment]
On the call today we discussed that the fall back to ORAS is not going to be supported. This issues needs to be updated to reflect that and the next update to the libraries will remove the ORAS artifact types and move to OCI with OCI image fallback.

**Comment by shizhMSFT** [comment]
Closing as all sub tasks are resolved.
