### ISSUE TITLE
Vote for release of ORAS-go v1.2.1

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-go#278]
Hi team @oras-project/oras-go-maintainers ,

Considering [ORAS-go v2](https://github.com/oras-project/oras-go#v2-experimental) is still experimental, ORAS-go v1 is stable and will be maintained by the ORAS community until ORAS v2 GA. Currently, ORAS-go v1 is not under active development, thus the ORAS community might only cut new releases to include necessary bug fixes.

There were two PRs merged since the ORAS-go 1.2.0 release:

- Bump docker/distribution to address [CWE-843](https://cwe.mitre.org/data/definitions/843.html) https://github.com/oras-project/oras-go/pull/276  
- Update implement info in the OCI store content implementation https://github.com/oras-project/oras-go/pull/187. 

Meanwhile, @viovanov and @mihaibuzgau also requested a new patch release of v1. So I want to request a new release `v1.2.1` in the community to include these two updates. 

We need at least 4 approvals from 6 @oras-project/oras-go-maintainers to vote for releasing and cutting the tag `v1.2.1` based on the [v1 branch](https://github.com/oras-project/oras-go/tree/v1).

- [ ]   Avi Deitcher (@deitch)
- [x]   Josh Dolitsky (@jdolitsky)
- [x]   Sajay Antony (@sajayantony)
- [x]   Shiwei Zhang (@shizhMSFT)
- [x]   Steve Lasker (@stevelasker)
- [ ]   Sylvia Lei (@Wwwsylvia)

Please respond LGTM or REJECT (with reasoning).

**Comment by jdolitsky** [comment]
LGTM

**Comment by SteveLasker** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
Thank you. Close it due to ORAS-go v1.2.1 was released https://github.com/oras-project/oras-go/releases/tag/v1.2.1
