### ISSUE TITLE
Wrap `errdef.ErrNotFound` with richer error message in order to distinguish platform not found and manifest not found

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#290]
Can we wrap `errdef.ErrNotFound` with richer error message in order to distinguish platform not found and manifest not found?

_Originally posted by @shizhMSFT in https://github.com/oras-project/oras-go/pull/282#discussion_r960337039_

**Comment by shizhMSFT** [comment]
@lizMSFT Could you follow up this one?

**Comment by lizMSFT** [comment]
> @lizMSFT Could you follow up this one?

No problem, I will take care of this issue.
