### ISSUE TITLE
Refactor `remote.TestRepositoryInterface`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#302]
`remote.TestRepositoryInterface` should test interface `oras.GraphTarget`. 
https://github.com/oras-project/oras-go/blob/d9a8f8245088a920e910f27c0fb4046ac53b84f8/registry/remote/repository_test.go#L121-L129
To avoid cyclic import, we will need to move this to a separate package, such as `remote_test`.

**Comment by Wwwsylvia** [comment]
@wangxiaoxuan273 Could you help to take a look?

**Comment by wangxiaoxuan273** [comment]
Sure.

**Comment by wangxiaoxuan273** [comment]
As per discussion, we also need to test `ReferenceParser` interface for `Repository` struct and `ManifestStore` struct.
