### ISSUE TITLE
Review `registry.ParseReference` function

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#303]
There might be some invalid forms that `registry.ParseReference` does not validate. We need to review this function and test it against more test cases.
https://github.com/oras-project/oras-go/blob/d9a8f8245088a920e910f27c0fb4046ac53b84f8/registry/reference.go#L93-L130

**Comment by nima** [comment]
I'll take this; please assign to me 🍉

**Comment by shizhMSFT** [comment]
One instance found by @lizMSFT is
```
localhost:5000/hello:sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Definitely, it is invalid. However, `ParseReference` returns no error.

**Comment by nima** [comment]
In the current state of the code, the string `` is resolved into its 3 components in the following way:

- reg: `localhost:5000`
- rep: `hello`
- ref: `sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

Meanwhile, I'll ask a related side-question: is it possible to declare form `B` "Invalid"?  It's ambiguous at best and seems unnecessary to support.

For reference:
```
// The parameter `artifact` is an opaque polymorphic string, composed of two
// other opaque tokens; namely `socketaddr` and `path`: These can in turn take
// on their own polymorphic forms.  To do this, the Backus–Naur Form (BNF)
// notation has been adopted, with the exception that *lowercase* labels here
// imply opaque values (composed of other components), and *uppercase* labels
// imply resolute/final values (can not be expanded further into subcomponents).
//
//	  <artifact> ::= <socketaddr> "/" <path>
//
//	<socketaddr> ::= <host> | <host> ":" <PORT>
//	      <host> ::= <ip> | <HOSTNAME> | <FQDN>
//	        <ip> ::= <IPV4-ADDR> | <IPV6-ADDR>
//
//	      <path> ::= <REPOSITORY> | <REPOSITORY> <reference>
//	 <reference> ::= "@" <digest> | ":" <TAG> "@" <DIGEST> | ":" <TAG>
//	    <digest> ::= <ALGO> ":" <HASH>
//
// That is, of all the possible forms that `path` can take, there are exactly 4
// that are considered valid.  Expanding the BNF notation for `path`, the 4 are:
//
//	<--- path --------------------------------------------> |  - Decode `path`
//	<=== REPOSITORY ===><--- reference -------------------> |    - Decode `reference`
//	<=== REPOSITORY ===> @ <------------------- digest ---> |      - Valid Form A
//	<=== REPOSITORY ===> : <!!! TAG !!!> @ <--- digest ---> |      - Valid Form B
//	<=== REPOSITORY ===> : <=== TAG ======================> |      - Valid Form C
//	<=== REPOSITORY ======================================> |    - Valid Form D
```

**Comment by nima** [comment]
> One instance found by @lizMSFT is
> 
> ```
> localhost:5000/hello:sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> ```
> 
> Definitely, it is invalid. However, `ParseReference` returns no error.

Anything else you can think of that we're missing from our tests @shizhMSFT? This turned out to be a somewhat unique special-case where the string is first allowed "in" by virtue of being deemed a *tag*, and later passes verification as a *digest*.

**Comment by shizhMSFT** [comment]
> Anything else you can think of that we're missing from our tests @shizhMSFT?

How do we deal with something like

```
localhost:5000/hello:
localhost:5000/hello@
localhost:5000/hello:@
```
?
