### ISSUE TITLE
Utility method for verifying content from reader

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#306]
When reading from the `io.ReadCloser` returned by `Fetch()` functions, it's recommended to verify the read content against the descriptor.
`oras-go` should provide a convenient utility method for verifying the content read from reader.

**Comment by shizhMSFT** [comment]
@wangxiaoxuan273 Could you help with this issue?

**Comment by wangxiaoxuan273** [comment]
Sure. Please assign this to me.
