### ISSUE TITLE
Return `errdef.ErrUnsupported` on `Delete()` if remote repository does not support delete

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#317]
When the remote does not support delete or has delete disabled, it will return `405 not supported`.
```
Error: failed to delete localhost:12900/0818hello@sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: DELETE "http://localhost:12900/v2/0818hello/blobs/sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855": unexpected status code 405: unsupported: The operation is unsupported.
```

We should return `errdef.ErrUnsupported` as a known error.

Original discussion: https://github.com/oras-project/oras/pull/493#issuecomment-1244930279

**Comment by yuehaoliang-microsoft** [comment]
I'm aware of the context of this issue, and will handle it.

**Comment by shizhMSFT** [comment]
> I'm aware of the context of this issue, and will handle it.

Many thanks on helping this. The code change is expected only in the file `registry/remote/repository.go`.

Please also follow up the related change in oras CLI.

**Comment by yuehaoliang-microsoft** [comment]
For my test case:

Before any change:
`Error: failed to delete localhost:12900/hello:v1: DELETE "http://localhost:12900/v2/hello/manifests/sha256:2e0e0fe1fb3edbcdddad941c90d2b51e25a6bcd593e82545441a216de7bfa834": unexpected status code 405: unsupported: The operation is unsupported.`

After I changed to use `errdef.ErrUnsupported` when `resp.StatusCode == 405`:
`Error: failed to delete localhost:12900/hello:v1: sha256:2e0e0fe1fb3edbcdddad941c90d2b51e25a6bcd593e82545441a216de7bfa834: unsupported`

Should there's be more information about it is the registry server that doesn't allow deletion?

**Comment by yuehaoliang-microsoft** [comment]
Maybe simplify it to be:
`Error: failed to delete localhost:12900/hello:v1: unsupported`
Or make it more informative, like:
`Error: failed to delete localhost:12900/hello:v1: unsupported: the remote server does not enable deletion`

**Comment by shizhMSFT** [comment]
> `return fmt.Errorf("%s: %w", target.Digest, errdef.ErrUnsupported)`

Looks good to me. CLI can have more verbose error message after checking `errors.Is()`.

**Comment by yuehaoliang-microsoft** [comment]
Proposed an idea for error message in ORAS CLI.

I locally override oras-go in oras `replace oras.land/oras-go/v2 => /home/yuehaoliang/oras-go` and tested this change.
<img width="652" alt="image" src="https://user-images.githubusercontent.com/109199020/190990983-f7355fa5-6da3-452c-8504-c6415b061fc6.png">
<img width="852" alt="image" src="https://user-images.githubusercontent.com/109199020/190991013-ae3b0aa0-2635-47d9-9e1b-5d9ffd27b35a.png">

**Comment by shizhMSFT** [comment]
Server returning `405 Method Not Allowed` does imply that such operation is unsupported.

For instance, ACR has a feature named [Lock a container image in an Azure container registry](https://learn.microsoft.com/azure/container-registry/container-registry-image-lock), which allows to disable delete and other operations. In such a case, the output looks like
```
$ oras manifest delete $reg/ubuntu:latest
Are you sure you want to delete the manifest "sha256:cef0c2cde57a973ed80513a7d3614bc654d9d6becad2c068c9328b41bb3f6713" and all tags associated with it? [y/N] y
Error: failed to delete ******.azurecr.io/ubuntu:latest: DELETE "https://******.azurecr.io/v2/ubuntu/manifests/sha256:cef0c2cde57a973ed80513a7d3614bc654d9d6becad2c068c9328b41bb3f6713": unexpected status code 405: registry disallowed operation: The operation is disallowed on this registry, repository or image. View troubleshooting steps at https://aka.ms/acr/faq/#why-does-my-pull-or-push-request-fail-with-disallowed-operation-
```
