### ISSUE TITLE
Missing `nil` checks

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#318]
For functions that take a pointer parameter, we should check if the parameter is a `nil`. If so, return early or throw an error, depending on the scenario.

For instance,

- [oras.WithTargetPlatform](https://github.com/oras-project/oras-go/blob/main/copy.go#L66)
- [oras.FilterAnnotation](https://github.com/oras-project/oras-go/blob/main/extendedcopy.go#L183)
- [oras.FilterArtifactType](https://github.com/oras-project/oras-go/blob/main/extendedcopy.go#L238)

**Comment by shizhMSFT** [comment]
@jasminetMSFT Could you help on this?

**Comment by jasminetMSFT** [comment]
Sure, I will work on it.
