### ISSUE TITLE
What's plan for stability?

### ISSUE THREAD

**Issue by mattfarina** [oras-project/oras-go#33]
The readme notes:

> 🚧 This project is currently under active development. The API may and will change incompatibly from one commit to another. 🚧

This is a blocker for using this package as a trusted source and releasing stable functionality based on it. Is there a plan to a 1.0.0? Will there be any API guarantees at any point coming up?

People want to put artifacts in OCI registries but, I think, that needs to happen based on a stable foundation. What's the plan to get there?

**Comment by scottrigby** [comment]
This has been addressed 🎈 
- #74 
- #75
- https://github.com/oras-project/oras-go/releases/tag/v1.0.0 

Thanks @mattfarina @sajayantony @jdolitsky and everyone
