### ISSUE TITLE
OCI store should support discovering predecessors that are not tagged

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#342]
Currently, when restoring from an existing OCI layout, the OCI store will index the predecessor relationships for all the manifests in `index.json`, which are tagged manifests.
However, the predecessors of manifests are usually not tagged and are not present in `index.json`. 
As a result, these predecessors will not be indexed, and they cannot be discovered by the `Predecessors()` function of the OCI store. This blocks scenarios like extended-copying a graph from an OCI store that is restored from an existing OCI layout to other Targets.

**Comment by shizhMSFT** [comment]
We can apply tag schema in the distribution-spec to OCI layout.

**Comment by shizhMSFT** [comment]
The implementation of `zot` gives an idea that we can store un-tagged manifests in the `index.json` so that predecessors can be indexed without a tag schema.
