### ISSUE TITLE
How to distinguish "unsupported manifest" error from other `400 Bad Request` errors on manifest push?

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#344]
Remote registries return `400 Bad Request` error on manifest push when:
1. The pushed manifest is malformed
2. The layers referenced by the manifest do not exist
3. The registry does not support the media type of the pushed manifest

Currently, `oras-go` is unable to distinguish case 3 from case 1 and 2 on manifest push.
This blocks the below scenario:

1. A client builds an artifact manifest and pushes is to a remote registry
2. The client finds that the registry does not support artifact manifest
3. The client fallback to push an image manifest to the registry

Related code:
https://github.com/oras-project/oras-go/blob/1969551cc3c77b46f09090f00360e8465871fe8f/registry/remote/repository.go#L1048-L1051

**Comment by nima** [comment]
> What would ECR return if we push a manifest, whose media type is unsupported by ECR?

ECR returns a `http.StatusBadRequest error, with a sub-error code of `UNSUPPORTED`.
