### ISSUE TITLE
Revisit `file.PackFiles()`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#345]
`file.PackFiles()` allows users to add files and pack a manifest quickly. But the current design might not be perfect. 
We should revisit it and think about if we should keep/refactor/deprecate it in `oras-go v2.0.0`.

https://github.com/oras-project/oras-go/blob/1969551cc3c77b46f09090f00360e8465871fe8f/content/file/file.go#L429-L443

**Comment by Wwwsylvia** [comment]
One use case of this function can be found [here](https://github.com/oras-project/oras-go/issues/341).

**Comment by shizhMSFT** [comment]
@Wwwsylvia I suggest removing this function, and adding an example instead.

**Comment by sajayantony** [comment]
+1 to an example with just one file add to show how someone can generate a manifest and to keep the lines of code less.
