### ISSUE TITLE
Deprecate the default artifact type `application/vnd.unknown.artifact.v1`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#346]
As per the latest [update ](https://github.com/opencontainers/image-spec/pull/967)on the image-spec, the `artifactType` field will be omitted if empty.
Hence, after the change is released, we can deprecate the default artifact type `application/vnd.unknown.artifact.v1` and just leave the user-provided `artifactType` as it is.
https://github.com/oras-project/oras-go/blob/1969551cc3c77b46f09090f00360e8465871fe8f/pack.go#L88-L91

**Comment by shizhMSFT** [comment]
Although `artifactType` can be omitted if empty, it is still marked as `SHOULD`. Therefore, it is better to have a value in it. I'd suggest close this issue.

**Comment by Wwwsylvia** [comment]
Closing as not needed.
