### ISSUE TITLE
`oras.Copy` should return error with detailed info implying where the failure happens

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-go#355]
For now `oras.Copy` will return all wrapped errors covering the whole call stack (e.g. http error code, response error) but not including contextual information like **on what node it's failing**. This missing information can be useful when the callee need to confirm where the copy fails. 

One use case is that oras cli need to fallbak to OCI image when pushing artifact is not supported. ECR may return `ErrorCodeUnsupported` but oras cli **should only fallback when the error happens on root node when copying**. We currently had a [work around](https://github.com/oras-project/oras/blob/990c84f4709ce4424eb11b4032770b19380c2c27/cmd/oras/push.go#L223-L235) to do the check but it can be simplified if oras-go can support it natively.

**Comment by shizhMSFT** [comment]
Closed by https://github.com/oras-project/oras/issues/782
