### ISSUE TITLE
Where is the actual readme?

### ISSUE THREAD

**Issue by simar7** [oras-project/oras-go#38]
Hello, 

I've been following the project readme as listed but it seems that the readme is severely out of date and many functions are either completely changed or removed altogether. This is the link I've been following: https://oras.land/client_libraries/go/

Where can I find a readme that would work with the latest release?

**Comment by shizhMSFT** [comment]
Please refer to the README.md for code documentation. For other docs, please visit https://github.com/oras-project/oras-www
