### ISSUE TITLE
Vote for ORAS-go 1.2.2 release:

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-go#388]
Hi team @oras-project/oras-go-maintainers ,

Considering [ORAS-go v2](https://github.com/oras-project/oras-go#v2-experimental) is still experimental, ORAS-go v1 is stable and will be maintained by the ORAS community until ORAS v2 GA. 

Currently, ORAS-go v1 is not under active development, the ORAS community might only cut new releases to include necessary bug fixes.

There were [four PRs merged](https://github.com/oras-project/oras-go/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies+label%3Av1) since the ORAS-go 1.2.1 release: 

![image](https://user-images.githubusercontent.com/40452856/208621365-72cea444-f355-4dcd-9b35-849f12e98a8e.png)

Meanwhile,  @lucacome also requested a new patch release of v1. So I want to request a new release `v1.2.2`.

We need at least 4 approvals from 6 @oras-project/oras-go-maintainers to vote for releasing and cutting the tag `v1.2.1` based on the [v1 branch](https://github.com/oras-project/oras-go/tree/v1).

- [ ]   Avi Deitcher (@deitch)
- [x]   Josh Dolitsky (@jdolitsky)
- [ ]   Sajay Antony (@sajayantony)
- [x]   Shiwei Zhang (@shizhMSFT)
- [x]   Steve Lasker (@stevelasker)
- [ ]   Sylvia Lei (@Wwwsylvia)

Please respond LGTM or REJECT (with reasoning).

**Comment by shizhMSFT** [comment]
LGTM

**Comment by SteveLasker** [comment]
Thanks @FeynmanZhou , pinging @sabre1041 , @scottrigby for Helm input

**Comment by sabre1041** [comment]
Helm test passed with current `v1` branch. The following checks were undertaken:

**Build**:
* Compilation
* Unit testing

**Integration Testing**
* Unauthenticated
    * Pushing, pulling, install, upgrade, template
* Authenticated
    * Pushing, pulling, install, upgrade, template

**Comment by SteveLasker** [comment]
based on @sabre1041, comment, I’m LGTM

**Comment by jdolitsky** [comment]
LGTM

**Comment by sajayantony** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Closing since [v1.2.2](https://github.com/oras-project/oras-go/releases/tag/v1.2.2) is released.
