### ISSUE TITLE
Referrers API support for OCI Layout

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#392]
The OCI layout can be viewed as a simplified local repository, which should also support the equivalence of [Referrers API](https://github.com/opencontainers/distribution-spec/blob/v1.1.0-rc1/spec.md#listing-referrers).

Proposal: Let [content/oci.Store](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0-rc.6/content/oci#Store) and [content/oci.ReadOnlyStore](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0-rc.6/content/oci#ReadOnlyStore) implement [registry.ReferrerFinder](https://pkg.go.dev/oras.land/oras-go/v2/registry#ReferrerFinder).

**Comment by shizhMSFT** [comment]
In terms of functionality, `Referrers()` is a subset of `Predecessors()`. Therefore, we can use `Predecessors()` to implement `Referrers()`.

**Comment by shizhMSFT** [comment]
There is a generic implementation in oras: https://github.com/oras-project/oras/blob/660d167c8434b19da455828e1f30ee7f3864638c/internal/graph/graph.go#L65

We can consider move and improve the above implementation to `oras-go`.

**Comment by wangxiaoxuan273** [comment]
I'd like to work on this.
