### ISSUE TITLE
Rearrange Project Layout

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#40]
## Introduction

First thing first, thank ORAS maintainers for separating the `oras` utility into `oras` CLI and `oras-go` library.

Since `oras-go` is a Go library and not a command line tool any more, the [standard project layout](https://github.com/golang-standards/project-layout) is not proper for this repository anymore.

Consider that the following import block
```go
import (
    "oras.land/oras-go"
    "oras.land/oras-go/content"
)
```
will be better than
```go
import (
    "oras.land/oras-go/pkg/oras"
    "oras.land/oras-go/pkg/content"
)
```

In the future, when `oras` reaches `v1.0.0` or even `v2.0.0`, it is better to have
```go
import (
    "oras.land/oras-go/v2"
    "oras.land/oras-go/v2/content"
)
```
than
```go
import (
    "oras.land/oras-go/v2/pkg/oras"
    "oras.land/oras-go/v2/pkg/content"
)
```

## Proposal

1. Promote `pkg/oras` to the root folder.
2. Promote `pkg` to the root folder so that there will be no more `pkg` folder.

## Benefits

Since we are decoupling the `containerd` while trying to introduce minimum backward compatibility issues, having a new project layout allows us to have new packages and the old ones at the same time. Then we can mark the old ones deprecated and slowly move them out.

## Discussion

All comments and suggestion are welcome! :tada:

**Comment by sajayantony** [comment]
@shizhMSFT - How can we capture the requirement of supporting tag to digest resolution. We need this in multiple places. 
Also a capability to get the manifest. Should I create another issue or can you add this to the design requirements.

**Comment by mnltejaswini** [comment]
If the tool can be used for basic registry operations like HEAD/GET on a manifest by both tag & digest reference, it increases the scope of its usage
