### ISSUE TITLE
Vote for v2.0.0 release 

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-go#415]
Hi @oras-project/oras-go-maintainers ,

All of the work items are completed in the [milestone of ORAS-go v2.0.0](https://github.com/oras-project/oras-go/milestone/11?closed=1) after 6 RC release iterations. This is the stable release of v2 so we need at least 4 approvals from 6 @oras-project/oras-go-maintainers to vote for tagging https://github.com/oras-project/oras-go/commit/96a37c2b359ac1305f70dc31b28c789688d77d0f as `v2.0.0`. See the detailed [change list](https://github.com/oras-project/oras-go/compare/v1.2.2...96a37c2b359ac1305f70dc31b28c789688d77d0f) compared to v1.2.2.

- [ ]   Avi Deitcher (@deitch)
- [ ]   Josh Dolitsky (@jdolitsky)
- [x]   Sajay Antony (@sajayantony)
- [x]   Shiwei Zhang (@shizhMSFT)
- [x]   Steve Lasker (@stevelasker)
- [x]   Sylvia Lei (@Wwwsylvia)

If you have any concerns, please let us know. Thanks! Please respond LGTM or REJECT (with reasoning).

**Comment by Wwwsylvia** [comment]
LGTM

**Comment by sajayantony** [comment]
LGTM

**Comment by jdolitsky** [comment]
Hi, I was involved in the earlier stages of the ORAS project, and yes, I did create the amazing logo.

I have not been active for some time now, and think it makes sense for me to step down as a maintainer of the project. The remaining maintainers could maybe nominate another member of the community to take the role if necessary. I shouldn't hold up votes like this as I haven't been following the progress.

**Comment by sajayantony** [comment]
Thanks for surfacing this up Josh and this conversation is probably an opportunity to ensure that the project is healthy as well. @FeynmanZhou will you surface this up during the next call and include others from the community on another issue, maybe in the community repo?

**Comment by FeynmanZhou** [comment]
> Thanks for surfacing this up Josh and this conversation is probably an opportunity to ensure that the project is healthy as well. @FeynmanZhou will you surface this up during the next call and include others from the community on another issue, maybe in the community repo?

Yes. We will follow the [governance guide](https://github.com/oras-project/community/blob/main/governance/GOVERNANCE.md#subproject-owners) to do this. 

Thank you @jdolitsky for your great contributions to ORAS-go at the beginning of this project. Would you be able to submit an [issue](https://github.com/oras-project/community/issues/new) to request to step down and move to emeritus?

**Comment by shizhMSFT** [comment]
We have super majority of votes and proceeded to release [v2.0.0](https://github.com/oras-project/oras-go/releases/tag/v2.0.0).

**Comment by deitch** [comment]
I am in the same spot as Josh, and Steve kindly reminded me to step in here (which, in itself, is a sign). I have a lot of interest in this project, but have not been giving it the time it deserves.
