### ISSUE TITLE
Downloading to locations independent of org.opencontainers.image.title

### ISSUE THREAD

**Issue by softpuff** [oras-project/oras-go#416]
If an example file is pushed from it's parent folder (like `oras push somedir/somefile.something`) that path is writen as annotationTitle and during pull it's downloaded to the same location (if -T flag is used or if it's not outside of workdir). I'm trying to find a way to download files and directories directly into workdir (using the same example, to download file `somefile.something` into directory I'm executing code from not to `somedir`). Possible solution is adding bool field to `File.store` struct and using just base from `org.opencontainers.image.title` joined with workdir like in #410

**Comment by shizhMSFT** [comment]
If the folder structure is required to be overridden when it is pulled, should we request the artifact publisher to re-create the artifact with a more reasonable folder structure? Although `oras` supports absolute path as the blob name, it is strongly discouraged. Those artifacts for public downloading should have relative paths.

If users do want to download the artifact regardless the blob names, it is suggested to use [oci](https://pkg.go.dev/oras.land/oras-go/v2/content/oci) stores.

**Comment by shizhMSFT** [comment]
Technically, we can flatten the folder structure of an artifact as you've suggested in #410. We require a reasonable user scenario for this kind of operations. /cc @FeynmanZhou

**Comment by softpuff** [comment]
Well particular scenario that I have is that we are using oci images to store configurations from different sources and they're pushed concurrently by other component. Because pushing component is operating in routines it can't cd before pushing so we're stuck with directory structure that we don't need. Other scenario from top of my head is pulling a copy somewhere and wishing to preserve original but I do believe this little feature would be useful in many occasions when the same data is consumed in different contexts

**Comment by softpuff** [comment]
thanks, that resolves my scenario

**Comment by shizhMSFT** [comment]
Closing as this issue is marked as resolved.

**Comment by Ern-st** [comment]
We've recently run into the same issue and we can't really change the way the title is generated, it's Microsoft Defender Vulnerability Management that creates a vulnerability report and attaches it to our images in Azure Container Registry

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "artifactType": "application/vnd.in-toto+json",
  "config": {
    "mediaType": "application/vnd.oci.empty.v1+json",
    "digest": "sha256:<redacted>",
    "size": 2,
    "data": "e30="
  },
  "layers": [
    {
      "mediaType": "application/vnd.in-toto+json",
      "digest": "sha256:<redacted>",
      "size": 7264,
      "annotations": {
        "in-toto.io/predicate-type": "https://in-toto.io/attestation/vulns/v0.2",
        "org.opencontainers.image.title": "/tmp/tmp1XnMTp.tmp",
        "report-type": "SoftwareInventoryAssessment",
        "scanner": "MDVM"
      }
    }
  ],
  "subject": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "digest": "sha256:<redacted>",
    "size": 5354
  },
  "annotations": {
    "in-toto.io/predicate-type": "https://in-toto.io/attestation/vulns/v0.2",
    "org.opencontainers.image.created": "2026-04-24T10:28:30Z",
    "report-type": "SoftwareInventoryAssessment",
    "scanner": "MDVM"
  }
}
```
