### ISSUE TITLE
oras.land/client_libraries/go: Documentation for the ORAS Go library

### ISSUE THREAD

**Issue by FBIanderson** [oras-project/oras-go#424]
this url is deprecated now, i can't use go sdk as the example shows , is there a new example

**Comment by Wwwsylvia** [comment]
Hi @FBIanderson, we are in progress to update the website.
You can refer to the [common example list](https://github.com/oras-project/oras-go#v2-stable) and the [Go Reference](https://pkg.go.dev/oras.land/oras-go/v2) for the latest examples. Please let us know if anything is missing.

**Comment by FBIanderson** [comment]
thank you very much

Lixia (Sylvia) Lei ***@***.***> 于2023年2月1日周三 15:11写道：
