### ISSUE TITLE
Shift Go Support Window to [1.19, 1.20] 

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#425]
[Go 1.20](https://go.dev/blog/go1.20) is released with [release notes](https://go.dev/doc/go1.20)!

It is time to shift the window for go support to `[1.19, 1.20]` by updating

- `go. mod`
- GitHub Actions

Although we will set `1.19` as the minimum version of `oras-go`, it is still possible to compile `oras-go` with go 1.18.

**Comment by Asmit2952** [comment]
Hey @shizhMSFT if this is a good-first-issue, can I work on it?

**Comment by shizhMSFT** [comment]
@Asmit2952 Sure! Thanks for contributing. BTW, we follow the go [release policy](https://go.dev/doc/devel/release#policy) for the support window.
