### ISSUE TITLE
oras copy error message is not clear enough

### ISSUE THREAD

**Issue by JeyJeyGao** [oras-project/oras-go#432]
I manully modified the `size` field of the index.json of OCI layout file to be an invalid value and got this error message.

```
oras cp --from-oci-layout out:latest --to-oci-layout out3:latest -d
Error: read failed: unexpected EOF
```

index.json file
```jsonc
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:ff43fa9e6ee876230e679f2ff7d2c61f3c43ca437d3cf46b93c28c2231ec9773",
      "size": 12401, // invalid size
      "annotations": {
        "io.containerd.image.name": "docker.io/library/latest:latest",
        "org.opencontainers.image.created": "2023-01-30T02:26:00Z",
        "org.opencontainers.image.ref.name": "latest"
      },
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    }
  ]
}
```
It looks like the error message is not clear enough.

**Comment by TerryHowe** [comment]
Do you have any suggestions on what would be more clear?

**Comment by JeyJeyGao** [comment]
> Do you have any suggestions on what would be more clear?

It looks like it did not validate the size otherwise it will return a more reasonable error. I think it should tell me what is not correct. For example, the oci layout is invalid, the index.json is invalid or the size is invalid.
