### ISSUE TITLE
Create E2E examples

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#434]
Currently we have several runnable examples for specific APIs. However, we don't have any E2E examples that demonstrates how the APIs can be used together.

**Comment by sparr** [comment]
Adding some narrative descriptions of example examples here would make it easier for a contributor to implement examples.

**Comment by wangxiaoxuan273** [comment]
I'd like to work on this.

**Comment by Wwwsylvia** [comment]
> Adding some narrative descriptions of example examples here would make it easier for a contributor to implement examples.

We can migrate the [existing quick start examples](https://oras.land/docs/Client_Libraries/go#quick-start) to the [go reference](https://pkg.go.dev/oras.land/oras-go/v2):

1. [Push files to a remote repository](https://oras.land/docs/Client_Libraries/go#push-files-to-a-remote-repository)
2. [Pull files from a remote repository](https://oras.land/docs/Client_Libraries/go#pull-files-from-a-remote-repository)
3. [Pull a docker or OCI image from a remote repository to a local OCI layout](https://oras.land/docs/Client_Libraries/go#pull-a-docker-or-oci-image-from-a-remote-repository)
4. [Pull an image using the docker credentials store](https://oras.land/docs/Client_Libraries/go#pull-an-image-using-the-docker-
credential-store)

And we can also have some examples like:
- Copy an image from an OCI layout tar archive to a remote repository

Please feel free to share any additional examples that you think would be helpful for users.

**Comment by Wwwsylvia** [comment]
We can also add the links to the new examples to the README: https://github.com/oras-project/oras-go#v2-stable
