### ISSUE TITLE
Documentation Link for orag-go sdk is broken in the readme file

### ISSUE THREAD

**Issue by khanjasir90** [oras-project/oras-go#437]
The documentation link for the oras-go sdk is broken and gives response of 404 page not found.
[Link to the broken link in readme](https://github.com/oras-project/oras-go/blob/main/README.md?plain=1#L48)

**Comment by khanjasir90** [comment]
@shizhMSFT i'll fix this up!

**Comment by shizhMSFT** [comment]
Can you reference the code in the issue description?

**Comment by khanjasir90** [comment]
[Link](https://github.com/oras-project/oras-go/blob/main/README.md?plain=1#L48)

**Comment by khanjasir90** [comment]
@shizhMSFT i have updated the issue description with the reference link to the broken docs url

**Comment by shizhMSFT** [comment]
Thank @khanjasir90 for finding this. Since `v2` succeeds the `v1`, the doc for `v1` is no long available. Therefore, we can safely remove that line.

https://github.com/oras-project/oras-go/blob/4a09c4d2468e5d6a25173a59d77785ee1af5a202/README.md?plain=1#L48

**Comment by khanjasir90** [comment]
@shizhMSFT cool will do that! btw is there any link to the v2 sdk so that we can add it to the readme file

**Comment by shizhMSFT** [comment]
Yes, it's [there](https://oras.land/client_libraries/0_go/).

**Comment by TerryHowe** [comment]
Might want to have a best practice in the docs site that if you move a file, provide a redirect
