### ISSUE TITLE
Add concurrency for tag/digest reading

### ISSUE THREAD

**Issue by TerryHowe** [oras-project/oras-go#445]
Add concurrency for reading tags/digests similar to the tagging concurrency.

Scan and resolve every tag in the list will degrade the performance. Below are some experiments I made based on the current implementation:
```shell
oras repo tags docker.io/library/alpine | wc
time oras repo tags docker.io/library/alpine:latest
oras repo tags mcr.microsoft.com/cbl-mariner/distroless/minimal | wc
time oras repo tags mcr.microsoft.com/cbl-mariner/distroless/minimal:1.0
``` 

On my computer , it takes DockerHub 47.442 seconds to scan 129 tags, and MCR 19.192 seconds to scan 141 tags.

_Originally posted by @qweeah in https://github.com/oras-project/oras/pull/800#discussion_r1105475134_

**Comment by shizhMSFT** [comment]
@TerryHowe Could you elaborate more on this feature request?
