### ISSUE TITLE
failed to open a read-only OCI store if `index.json` doesn't exist

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-go#449]
[oci.NewFromFS](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0/content/oci#NewFromFS) and [oci.NewFromTar](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0/content/oci#NewFromTar) will always validate the existence of `index.json`. We might need to loose this check since it is possible to have an OCI image layout with only blobs but no manifest stored.

**Comment by Wwwsylvia** [comment]
[`index.json`](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc2/image-layout.md#indexjson-file) is a required file for OCI layout. 
Instead of relaxing the check, I think we should automatically generate the `index.json` instead even if there is no manifest stored in the layout.

**Comment by qweeah** [comment]
> automatically generate the `index.json` even if there is no manifest stored in the layout.

👍indeed, just double checked the [OCI spec](https://github.com/opencontainers/image-spec/blob/v1.0/image-layout.md#content), `indes.json` MUST exist.
