### ISSUE TITLE
Feature Request: Add observability in http retry client 

### ISSUE THREAD

**Issue by akashsinghal** [oras-project/oras-go#471]
Currently, the http retry mechanism is implemented in the `Transport`'s `RoundTrip()` method. It would be nice to be able to retrieve the status code returned within each retry attempt and collect other fields such as request duration and request URI. This can be very helpful for generating metrics such as RPS, request duration, and throttling via 429.

**Comment by akashsinghal** [comment]
cc: @Wwwsylvia

**Comment by shizhMSFT** [comment]
> It would be nice to be able to retrieve the status code returned within each retry attempt and collect other fields such as request duration and request URI.

This can be simply achieved by wrapping the existing default predicate.

**Comment by akashsinghal** [comment]
@shizhMSFT Thanks for the response! Looks like a custom Predicate will get the status code and the request URI (potentially). Any recommendations for easily getting the duration?

**Comment by shizhMSFT** [comment]
> @shizhMSFT Thanks for the response! Looks like a custom Predicate will get the status code and the request URI (potentially). Any recommendations for easily getting the duration? This is not as important for my use case. You'd ideally want to time wrap the `roundTrip` function call to see how long the whole operation takes (including connection establishing, DNS lookup, etc.)

This is beyond the scope of oras. However, you still can build your own `RoundTripper` to record or emit the duration. Note that you can leverage `context.Context` in `http.Request` to track context.

**Comment by akashsinghal** [comment]
I was able to implement a custom retry predicate that wrapped the default one. Using that, I was able to extract the per request method and response status. That's sufficient for my purposes for now. I think it's fine to close this issue now. Thanks! cc: @Wwwsylvia

**Comment by Wwwsylvia** [comment]
Closing this issue as it's out of the scope of `oras-go`.
