### ISSUE TITLE
Feature Request: err type for dangling referrers index deletion failure

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-go#479]
If referrer API not supported and referrers need to be updated, oras-go will 1) update the referrer index and 2) cleanup the dangling one.

https://github.com/oras-project/oras-go/blob/336b9fb9c68c7228158dcd3c5e7735a0f624d279/registry/remote/repository.go#L1271-L1276

It would be great if oras-go can expose a certain typed error when the cleanup operation fails, so caller client can decide whether to terminate, or ignore the error, or do ad-hoc garbage collection on caller side.

**Comment by TerryHowe** [comment]
Specifically https://github.com/oras-project/oras/pull/921#discussion_r1161136540

**Comment by patrickzheng200** [comment]
We have the same request from Notation: https://github.com/notaryproject/notation/issues/615

**Comment by SteveLasker** [comment]
Is there a reason we're deleting "history" for updating the index? 
I realize this is a "backwards compat" type feature, where registries that support the referrers API would dynamically generate the response. It just feels wrong to have content deleted from a registry on push.

**Comment by qweeah** [comment]
> Is there a reason we're deleting "history" for updating the index?

Since there are no API users can use to discover the obsolete referrers index, IMHO oras should treat those more like garbage rather than history. 

What is suggested in this issue is how we clean up garbage index: before we make it mandatory, after we do it in a best-effort way.

**Comment by SteveLasker** [comment]
> Since there are no API users can use to discover the obsolete referrers index, IMHO oras should treat those more like garbage rather than history.

Do you need to know about the historic changes. Or, do you only care what the current tag is for that index? Once you push an updated index, with the tag pattern, the old index is now orphaned, and not as relevant, nor is it something a client should be deleting any more than a client deletes the old manifest of a tag when a new one is pushed.
Registries like Docker Hub actually track the tag history, which is a cool feature. 

In either case, this is a philosophical discussion: IMO, clients that push content should not be deleting something.

**Comment by qweeah** [comment]
> IMO, clients that push content should not be deleting something.

Totally agree. Making deletion-error-handling optional can be the first step of making deletion optional, which means this issue doesn't go against your vision on pushing content without deleting something.

**Comment by Wwwsylvia** [comment]
> Do you need to know about the historic changes. Or, do you only care what the current tag is for that index? Once you push an updated index, with the tag pattern, the old index is now orphaned, and not as relevant, nor is it something a client should be deleting any more than a client deletes the old manifest of a tag when a new one is pushed. Registries like Docker Hub actually track the tag history, which is a cool feature.
> 
> In either case, this is a philosophical discussion: IMO, clients that push content should not be deleting something.

To my understanding, the referrers index is an implementation detail that end users should not be aware of.

I agree that clients that push content should not be deleting anything. But it's also strange that the client leaves invisible garbage in the user's registry every time it pushes a manifest.

IMHO making deletion optional could be a balanced approach. Perhaps we could provide an option for users to enable or disable automatic garbage collection, while carefully considering the default value of this option.
 Do you think we should make `oras-go` not to delete the garbage referrers index by default?

**Comment by SteveLasker** [comment]
> I agree that clients that push content should not be deleting anything. But it's also strange that the client leaves invisible garbage in the user's registry every time it pushes a manifest.

The list of indexes is a design choice for backwards compat. A registry that supports the referrers API would not need these indexes. I like to call these zombies objects that get left behind.

There are other zombie objects that get left behind for registries that get new information pushed that it wasn't expecting.
Using the tag pattern for pushing references, the registry has no knowledge it has references.

You push the following:
- `registry.acme-rockets.io/net-monitor:v1`
- registry.acme-rockets.io/net-monitor:[digest of v1].sig`
- registry.acme-rockets.io/net-monitor:[digest of v1].spdx` 
- registry.acme-rockets.io/net-monitor:[digest of v1].vex` 
- registry.acme-rockets.io/net-monitor:[digest of v1].scan-report` 

When the user goes to archive, or purge `registry.acme-rockets.io/net-monitor:v1`, the list of references (zombied artifacts) are also left behind.

The other issue registries and users will hit is RBAC permissions. Following the best practice for minimal permissions, users should be given PUSH rights, but not DELETE rights. The registry supports DELETE, but the user shouldn't have DELETE rights. Would that return the same error code for ORAS to process? Or, should this not be a path we go down, as backwards compat is a design choice.

My point is this is a design choice (a bad design choice IMO) for how OCI is choosing to push content to registries that don't know to support references.

IMO, registries should opt-into support, as it's a critical business need, and pushing content to registry that wasn't designed to handle it is a not a path we should go down. 
If we are going down this road, we should not attempt to mix modes. If the registry allows anything, it gets what it asked for. 
ORAS should not attempt to work around this design choice and should not attempt to delete the zombie indexes.
