### ISSUE TITLE
Bug: `auth.StaticCredential` does not properly handle `docker.io`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#484]
When [`remote.Registry`](https://github.com/oras-project/oras-go/blob/main/registry/remote/registry.go#L38) is accessing `docker.io`, it actually issues requests to `registry-1.docker.io`. Therefore, it expects the [`client.Credential`](https://github.com/oras-project/oras-go/blob/main/registry/remote/auth/client.go#L83-L88) to return the credential for `registry-1.docker.io` instead of `docker.io`. 
But the current implementation of [`auth.StaticCredential`](https://github.com/oras-project/oras-go/blob/main/registry/remote/auth/client.go#L57-L65) does not handle this case.

**Comment by zong-zhe** [comment]
Hello, if this bug will be fixed recently? My work is blocked by this bug.

**Comment by Wwwsylvia** [comment]
One of the workarounds before this bug gets fixed is that, passing `repo.Reference.Host()` instead of registry name to `StaticCredential()`.

 ```go
	repo, _ := remote.NewRepository("docker.io/library/hello-world")
	repo.Client := &auth.Client{
                // other fields...
		Credential: auth.StaticCredential(repo.Reference.Host(), cred),
	}
```

**Comment by qweeah** [comment]
Sorry I don't get the workaround. Shouldn't `repo.Reference.Host()` always be docker.io?

**Comment by Wwwsylvia** [comment]
[`repo.Reference.Host()`](https://github.com/oras-project/oras-go/blob/main/registry/reference.go#L235C1-L240) maps `docker.io` to `registry-1.docker.io` internally.
