### ISSUE TITLE
[Epic] ORAS Go Library Revamp

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#49]
Targeting releasing `v2.0.0`, it is important to stabilize the `oras-go` library with the following criteria since `oras-go` is and will be used as a fundamental building block of production projects and even security products:

- Simple to use.
- Fewer dependencies.
  - More dependencies imply more maintenance work.
  - We need to release frequently just to update the dependencies if there are updates, especially security updates.
- No breaking changes on minor releases.
  - We can start with a few exported packages, and develop or export new packages slowly.
- Well tested.
- Well documented.

This issue is used to track the process of the `oras-go` revamp in order to make `oras-go` meeting the above releasing criteria. Tasks are created as follows:

- Milestone 1
  - [x] #50 
  - [x] #62 
- Milestone 2
  - [x] #52
  - [x] #53 
- Milestone 3
  - [x] #54 
  - [x] #55 
  - [x] #56 
- Milestone 4
  - [x] #57 
  - [x] #58 
- Milestone 5
  - [x] #59 
  - [x] #60 
  - [x] #61 
- Milestone 6
  - [x] #63

/cc @sajayantony @SteveLasker @jdolitsky @deitch @northtyphoon

**Comment by sajayantony** [comment]
@shizhMSFT Which item do you consider things like retrieving manifests from local or remote target?

**Comment by SteveLasker** [comment]
looks good. 
Where would you see unit tests being added for stability to changes?  
Is the expectation that each milestone can be validated with the oras client?

**Comment by shizhMSFT** [comment]
> @shizhMSFT Which item do you consider things like retrieving manifests from local or remote target?

Manifests are modeled as blobs. Therefore, retrieving manifests can be done by retrieving the blob. Since target has a tag resolver, manifests can be retrieved by generic tags.

**Comment by shizhMSFT** [comment]
> Where would you see unit tests being added for stability to changes?

The unit tests will be added in the corresponding go packages.

> Is the expectation that each milestone can be validated with the oras client?

Milestones here are like stages. We can start updating `oras` CLI when the milestone 4 is completed.

**Comment by shizhMSFT** [comment]
Closing as all issues are resolved.
