### ISSUE TITLE
Update README to recommend `oras-credentials-go`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#493]
Once we release the first version of [`oras-credentials-go`](https://github.com/oras-project/oras-credentials-go), we should update the README of `oras-go` to recommend it.

**Comment by sparr** [comment]
To clarify, do you mean v1.0 or sooner?

**Comment by shizhMSFT** [comment]
Closing this issue since we plan to merge `oras-credentials-go` to `oras-go`.
