### ISSUE TITLE
Upgrading to new OCI 1.1 spec

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#494]
A new release candidate of OCI 1.1 spec is released.
- [image-spec v1.1.0-rc.3](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc.3)
- [image-spec v1.1.0-rc4](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc4)
- [distribution-spec v1.1.0-rc.2](https://github.com/opencontainers/distribution-spec/releases/tag/v1.1.0-rc.2)
- [distribution-spec v1.1.0-rc.3](https://github.com/opencontainers/distribution-spec/releases/tag/v1.1.0-rc.3)

We need to discuss how `oras-go` should support / implement the latest release candidate, or we should hold on for the stable release.

---

### `image-spec`: `v1.1.0-rc2` --> `v1.1.0-rc4`

- **BREAKING CHANGE** Removed artifact manifest
- **BREAKING CHANGE** Removed pre-defined annotation keys
  - `org.opencontainers.artifact.created`
  - `org.opencontainers.artifact.description`
  - `org.opencontainers.referrers.filtersApplied`
- Minimum golang version changed to `1.18`
- Non-distributable layers a.k.a. foreign layers are deprecated
- Introduced [empty descriptor](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/manifest.md#guidance-for-an-empty-descriptor)
  - Media type: `application/vnd.oci.empty.v1+json`
- `artifactType` field is introduced to the [image manifest](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/manifest.md#image-manifest). This field MUST be set if the config media type is set to empty
- `artifactType` and `subject` fields are introduced to the [image index](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/image-index.md)
- `layers` field of an image manifest SHOULD NOT be empty, which was a MUST. If the config media type is `application/vnd.oci.image.config.v1+json`, `layers` MUST NOT be empty.
- Introduced [Guidelines for Artifact Usage](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/manifest.md#guidelines-for-artifact-usage)

Full change set: https://github.com/opencontainers/image-spec/compare/v1.1.0-rc2...v1.1.0-rc4

### `distribution-spec`: `v1.1.0-rc1` --> `v1.1.0-rc.3`

- Removed docs to the [OCI Artifacts](https://github.com/opencontainers/artifacts) repository
- Updated conformance tests
- **BREAKING CHANGE** Removed artifact manifest
- Introduced the `OCI-Chunk-Min-Length` header
- Introduced new endpoint `end-13`: `GET /v2/<name>/blobs/uploads/<reference>`. 
  > **Note** This endpoint exists in the [Docker Registry HTTP API V2](https://docs.docker.com/registry/spec/api/#get-blob-upload)
- **IMPORTANT** The `OCI-Subject` header is returned on PUT manifest with `subject` if the remote registry supports Referrers API.
- **BREAKING CHANGE** Applying filters on the Referrers API will not return a result JSON with the annotation `org.opencontainers.referrers.filtersApplied`. Instead, the registry server returns a header `OCI-Filters-Applied`.
- Introduced `Warning` headers
- Minimum golang version changed to `1.18`
- Repository name is [relaxed](https://github.com/opencontainers/distribution-spec/blob/79571f3211c620a7b84fcc8a949577e06b36db1e/spec.md#pull). However, it is still a subset of the docker spec. Related `oras-go` code:
  https://github.com/oras-project/oras-go/blob/0e20275bbbd71f4619d9c1b9da150c4f586dff3b/registry/reference.go#L30-L37

Full change set: https://github.com/opencontainers/distribution-spec/compare/v1.1.0-rc1...v1.1.0-rc.3

---

### `image-spec`: `v1.1.0-rc2` --> `v1.1.0-rc.3`

- **BREAKING CHANGE** Removed artifact manifest
- **BREAKING CHANGE** Removed pre-defined annotation keys
  - `org.opencontainers.artifact.created`
  - `org.opencontainers.artifact.description`
  - `org.opencontainers.referrers.filtersApplied`
- Minimum golang version changed to `1.18`
- Non-distributable layers a.k.a. foreign layers are deprecated
- Introduced [scratch config](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc.3/manifest.md#example-of-a-scratch-config-or-layer-descriptor)
  - Media type: `application/vnd.oci.scratch.v1+json`
- `artifactType` field is introduced to the [image manifest](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc.3/manifest.md#image-manifest). This field MUST be set if the config media type is set to scratch
- `layers` field of an image manifest SHOULD NOT be empty, which was a MUST. If the config media type is `application/vnd.oci.image.config.v1+json`, `layers` MUST NOT be empty.
- Introduced [Guidelines for Artifact Usage](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc.3/manifest.md#guidelines-for-artifact-usage)

Full change set: https://github.com/opencontainers/image-spec/compare/v1.1.0-rc2...v1.1.0-rc.3

### `image-spec`: `v1.1.0-rc.3` --> `v1.1.0-rc4`

- `artifactType` and `subject` fields are introduced to the [image index](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/image-index.md)
- scratch config is changed to [empty descriptor](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/manifest.md#guidance-for-an-empty-descriptor)
  - Media type: `application/vnd.oci.empty.v1+json`

Full change set: https://github.com/opencontainers/image-spec/compare/v1.1.0-rc.3...v1.1.0-rc4

### `distribution-spec`: `v1.1.0-rc1` --> `v1.1.0-rc.2`

- Removed docs to the [OCI Artifacts](https://github.com/opencontainers/artifacts) repository
- Updated conformance tests
- **BREAKING CHANGE** Removed artifact manifest
- Introduced the `OCI-Chunk-Min-Length` header
- Introduced new endpoint `end-13`: `GET /v2/<name>/blobs/uploads/<reference>`. 
  > **Note** This endpoint exists in the [Docker Registry HTTP API V2](https://docs.docker.com/registry/spec/api/#get-blob-upload)
- **IMPORTANT** The `OCI-Subject` header is returned on PUT manifest with `subject` if the remote registry supports Referrers API.
- **BREAKING CHANGE** Applying filters on the Referrers API will not return a result JSON with the annotation `org.opencontainers.referrers.filtersApplied`. Instead, the registry server returns a header `OCI-Filters-Applied`.
- Introduced `Warning` headers
- Minimum golang version changed to `1.18`

Full change set: https://github.com/opencontainers/distribution-spec/compare/v1.1.0-rc1...v1.1.0-rc.2

### `distribution-spec`: `v1.1.0-rc.2` --> `v1.1.0-rc.3`

- Repository name is [relaxed](https://github.com/opencontainers/distribution-spec/blob/79571f3211c620a7b84fcc8a949577e06b36db1e/spec.md#pull). However, it is still a subset of the docker spec. Related `oras-go` code:
  https://github.com/oras-project/oras-go/blob/0e20275bbbd71f4619d9c1b9da150c4f586dff3b/registry/reference.go#L30-L37

Full change set: https://github.com/opencontainers/distribution-spec/compare/v1.1.0-rc.2...v1.1.0-rc.3

**Comment by shizhMSFT** [comment]
Resolving this issue resolves
- #491
- #492

**Comment by rchincha** [comment]
`zot` depends on this library to support ORAS artifacts. So a rc or a branch that removes/fixes at least the symbols much appreciated.

For example:
https://github.com/oras-project/oras-go/blob/main/internal/descriptor/descriptor.go#L73

**Comment by shizhMSFT** [comment]
@rchincha The PR #496 is going to fix that.

**Comment by andaaron** [comment]
Hi,

We're testing the image spec master branch on `zot`, and we noticed this constant was removed from the spec:
there is a constant which got removed from the spec: https://github.com/opencontainers/image-spec/commit/7f43cb4fdf597b591197b46b4d67c2b6797de237

And is currently used in:
https://github.com/oras-project/oras-go/blob/2e7b65f1b60d11cd861ce6b68bc53e23a1fd9306/pack.go#L93

**Comment by Wwwsylvia** [comment]
@andaaron Thanks for the reminder! We will fix that in the upcoming versions.

**Comment by Wwwsylvia** [comment]
For the next minor version of `oras-go`, we will update it to comply with [`image-spec v1.1.0-rc4`](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc4) and [the upcoming `distribution-spec v1.1.0-rc3`](https://github.com/opencontainers/distribution-spec/pull/433). The updated version will remain compatible with [`image-spec v1.1.0-rc2`](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc2) and [`distribution-spec v1.1.0-rc1`](https://github.com/opencontainers/distribution-spec/releases/tag/v1.1.0-rc1), and will not introduce any breaking changes.

The required changes for `oras-go` include:

- [ ] Upgrade to the latest image spec and fix missing types
- [ ] Support Image Index with subject
- [ ] Update `oras.Pack` to comply with the latest spec
- [ ] Update the implementation of Referrers API (#443)
- [ ] Update the implementation of pushing manifest
- [ ] Update the implementation of deleting manifest
- [ ] Support `Warning` headers (#469)

**Comment by shizhMSFT** [comment]
Closing this issue as `oras-go` has been update-to-date with `image-spec v1.1.0-rc4` and `distribution-spec v1.1.0-rc3`.
