### ISSUE TITLE
Vote for release of `v2.1.0`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#497]
At least 3 approvals are needed from the 4 owners for tagging [8aed964](https://github.com/oras-project/oras-go/tree/8aed9643987df1bc49365fb21d48a90e1f4c0df6) as `v2.1.0`.

- [x] Sajay Antony (@sajayantony)
- [x] Shiwei Zhang (@shizhMSFT)
- [x] Steve Lasker (@SteveLasker)
- [x] Sylvia Lei (@Wwwsylvia)

See [the change log](https://github.com/oras-project/oras-go/compare/v2.0.2...8aed9643987df1bc49365fb21d48a90e1f4c0df6) for more details.

Release draft is also [available](https://github.com/oras-project/oras-go/releases/tag/untagged-ca5bb4ebca3aa249ed4d).

Please respond LGTM or REJECT (with reasoning).

**Comment by SteveLasker** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
LGTM but I am not an ORAS-go maintainer.

**Comment by sajayantony** [comment]
LGTM for 8aed9643987df1bc49365fb21d48a90e1f4c0df6

**Comment by ytimocin** [comment]
> LGTM but I am not an ORAS-go maintainer.

Same but LGTM too :)

**Comment by Wwwsylvia** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Released [v2.1.0](https://github.com/oras-project/oras-go/releases/tag/v2.1.0)
