### ISSUE TITLE
Docker compatibility of v1.2.3 to docker v24.0.2

### ISSUE THREAD

**Issue by chenco47** [oras-project/oras-go#551]
Hi, It looks like oras v1.2.3 is not compatible with docker (github.com/docker/docker v24.0.2+incompatible)

go build
# oras.land/oras-go/pkg/auth/docker
../../../go/pkg/mod/oras.land/oras-go@v1.2.3/pkg/auth/docker/login.go:86:39: cannot use remote (variable of type *"github.com/docker/docker/registry".Service) as type "github.com/docker/docker/registry".Service in argument to c.loginWithTLS

Any way to solve it without downgrading the docker version? (impossible at the moment)

**Comment by pierlucg1047** [comment]
Why was this closed?

**Comment by xor22h** [comment]
Probably because it's duplicate of: https://github.com/oras-project/oras-go/pull/527
