### ISSUE TITLE
Upgrade to `image-spec v1.1.0-rc5`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#599]
[`image-spec v1.1.0-rc5`](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc5) has just been released.
The changes related to ORAS include:

- [Guidance for Artifacts Authors](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc5/artifacts-guidance.md) is introduced
- A decision tree is added in the [Guidelines for Artifact Usage](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc5/manifest.md#guidelines-for-artifact-usage) section in `manifest.md`
- String constants ["index.json"](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc5/specs-go/v1/layout.go#L22-L23) and ["blobs"](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc5/specs-go/v1/layout.go#L24-L25) are introduced
- [`MediaType`](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc5/specs-go/v1/descriptor.go#L23-L24) became a required field in `Descriptor`

Change log between `v1.1.0-rc4` and `v1.1.0-rc5`: https://github.com/opencontainers/image-spec/compare/v1.1.0-rc4...v1.1.0-rc5

**Comment by shizhMSFT** [comment]
Nice summary, @Wwwsylvia. Let's upgrade oras-go to `image-spec v1.1.0-rc5`accordingly.
