### ISSUE TITLE
Update Example

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#60]
Once we have the least code working, we should update the examples so that people can try themselves.

Examples (originally from @sajayantony 's list):

- [x] Download Manifest
- [x] Download a Blob given the digest
- [x] Put Manifest
- [x] Create manifest with Annotation
- [x] Upload Blob
- [x] Upload Manifest with blob
- [x] Copy Artifact
- [x] Insecure TLS / Plain HTTP
- [ ] HTTP Client Configuration

**Comment by sajayantony** [comment]
Add the list of items we potentially need as examples - 

# ORAS API Usecases

The following usecase can help define the list of examples that a new developer should be able to refer. 

1. Download Manifest
2. Download a Blob given the digest 
3. Put Manifest
4. Create manifest with Annotation
5. Upload Blob
6. Upload Manifest with blob
7. Copy Artifact
8. Upload manifest with reference 
9. Download reference manifest
10. Download blob of reference manifest
11. Copy reference 
12. Copy artifact and references


## Authentication tokens 
1. Get token for operation with scopes. 
2. Validate cross mount 

### Example Permutations 
1. Auth required for pull/push 
2. Insecure planHttp

**Comment by shizhMSFT** [comment]
Assigning this item to @qweeah.

**Comment by qweeah** [comment]
Ack

**Comment by sajayantony** [comment]
@qweeah - can you include GetManifest in the examples.

**Comment by qweeah** [comment]
> @qweeah - can you include GetManifest in the examples.

@sajayantony I think it's covered by [Example_pullByTag](https://github.com/oras-project/oras-go/blob/main/registry/remote/example_test.go#L490) and [Example_pullByDigest](https://github.com/oras-project/oras-go/blob/main/registry/remote/example_test.go#L523)

**Comment by wangxiaoxuan273** [comment]
> @wangxiaoxuan273 Could you help sweeping all the scenarios and add examples for them?

Sure. Please assign this to me.

**Comment by Wwwsylvia** [comment]
I just noticed that there is no item related to `referrers` in the example list. 
In the following items, does `artifact reference` mean `subject` here? Or do we actually mean `referrers`?  
-  Upload artifact reference manifest
-  Download artifact reference manifest
-  Download blob of artifact reference manifest
-  Copy reference
-  Copy artifact and references

The term `reference` seems to represent the artifact referencing the given manifest (which is a `referrer` of the given manifest) in [ORAS Artifact Scenarios](https://github.com/oras-project/artifacts-spec/blob/main/scenarios.md#oras-artifact-scenarios).  I'm confused by the terms we are using here.

**Comment by wangxiaoxuan273** [comment]
[ExampleRepository_Fetch_layer](https://github.com/oras-project/oras-go/blob/5b0f92b879ebe7b478dbae7d08d4a4a925085742/registry/remote/example_test.go#L380) is an example of `Download a Blob given the digest`, so this item should be checked.

**Comment by shizhMSFT** [comment]
Closing as "HTTP Client Configuration" is tracked by #182 separately.
