### ISSUE TITLE
Listing all repositories under a GitHub Container Registry (ghcr.io/org-name)

### ISSUE THREAD

**Issue by ytimocin** [oras-project/oras-go#621]
I was wondering if there is a way to list all the repositories under a GitHub Container Registry.

**What am I trying to accomplish?**
* List all the repositories under our organization's container registry.
* Filter all the repositories based on a query (like get me all the repositories that start with the letter **A**).
* Get all the images that are tagged as latest from the filtered list (in step 2).

**What have I tried so far?**
* We are passing our organization name into the remote.NewRegistry function like (**remote.NewRegistry("ghcr.io/org-name")**).
* The registry can't be validated.

Any help would be appreciated.

**Comment by TerryHowe** [comment]
See the CLI `oras repo ls` but I think you will find that most major repositories do not implement that.

**Comment by Wwwsylvia** [comment]
Hi @ytimocin, such operation requires support from the registry side. But unfortunately, Github Container Registry (`ghcr.io`) doesn't seem to support listing repositories through the `/v2/_catalog` API yet.  

I found this discussion thread in the GitHub community: https://github.com/orgs/community/discussions/26299, you may want to take a look.

**Comment by TerryHowe** [comment]
Reopen if there is anything else on this.

**Comment by ytimocin** [comment]
Hi @TerryHowe and @Wwwsylvia! Thank you so much for your replies. I guess I will choose the repository path and implement the solution in another way. Great [docs](https://oras.land/docs/category/oras-commands) by the way! Have a good day!
