### ISSUE TITLE
`oci.Storage.Delete()` should return `ErrNotFound` if target is not present in the storage

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-go#626]
In the current implementation, a `*PathError` will be return if `target` is not present in the storage, which is not user-friendly.

https://github.com/oras-project/oras-go/blob/0f1dc30a0fd713f3bafcf3bd52693b2e8a8a6fa5/content/oci/storage.go#L109-L117

**Comment by wangxiaoxuan273** [comment]
I'd like to work on this.
