### ISSUE TITLE
Rename `ErrSkipDesc` to `SkipNode`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#634]
#631 exports `errSkipDesc` to `ErrSkipDesc` so that copy can be skipped for mounting. However, `ErrSkipDesc` is not a real error that should be returned by any function. 

I have looked into the golang built-in package [`io/fs`](https://pkg.go.dev/io/fs#pkg-variables) and found `SkipAll` and `SkipDir`. To have consistent naming as the build-in packages, I propose that we should rename `ErrSkipDesc` to ~~`SkipDesc`~~ `SkipNode` (as discussed in comment section).

```go
var SkipAll = errors.New("skip everything and stop the walk")
var SkipDir = errors.New("skip this directory")
```

@Wwwsylvia @ktarplee Any comments?

**Comment by ktarplee** [comment]
@shizhMSFT I do like the name `SkipDesc` better than `ErrSkipDesc` but maybe the abbreviation needs to be dropped as well.  So I actually prefer `SkipDescriptor` for clarity.

**Comment by shizhMSFT** [comment]
`SkipDescriptor` sounds good to me.

**Comment by ktarplee** [comment]
Maybe `SkipNode` is a better name since we are actually skipping the node described by the descriptor and not the descriptor itself.

**Comment by sajayantony** [comment]
For API choices it always easier when we look at it in the context of code. Can we write up a small code block that would use SkipNode or skipDescriptor?

**Comment by ktarplee** [comment]
> For API choices it always easier when we look at it in the context of code. Can we write up a small code block that would use SkipNode or skipDescriptor?

You see a use of `ErrSkipDesc` in #632

**Comment by shizhMSFT** [comment]
The name `SkipNode` sound more reasonable to me as we are copying graphs.

**Comment by Wwwsylvia** [comment]
`SkipNode` sounds good to me.
