### ISSUE TITLE
Adapters for containerd remotes.Resolver

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#64]
Optionally, we can have an adaptor example in the `example` folder to adapt `remotes.Resolver` to our `Target` interface if users insist to use `containerd` implementation. Since  the `example` folder is a nested module, it will not impact the dependencies of the main module.

**Comment by deitch** [comment]
I like this idea. The only suggestion I would have is to put it in a different folder. `examples` is treated as, well, examples, not necessarily part of production code. Perhaps `adapters/containerd/`, and we can have other future `adapters/*/` if needed? It still would be a nested module, but would have a pathing that indicates it matters.

**Comment by shizhMSFT** [comment]
Instead of a nested module, I am considering put those adapters in a different repository or repositories. It will be clearer and easier to maintain.

Quoted from the [Multi-Module Repositories](https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories) doc,

> ### Should I have multiple modules in a single repository?
> Adding modules, removing modules, and versioning modules in such a configuration require considerable care and deliberation, so it is almost always easier and simpler to manage a single-module repository rather than multiple modules in an existing repository.

The above doc also points out two major scenarios for the nested modules. **Example code** is one of them. The reason is pretty simple that we don't need to care about the security vulnerabilities in the example codes as they are just examples.

**Comment by sajayantony** [comment]
Should we close this issue since we are now at the point of having removed containerd overall.

**Comment by shizhMSFT** [comment]
Closing this issue since users can opt to oras-go `v1` for `containerd`. `containerd` support is completely dropped for `v2`.
