### ISSUE TITLE
should forbid a symlink containing a symlink when pushing

### ISSUE THREAD

**Issue by wangxiaoxuan273** [oras-project/oras-go#646]
By design, a symlink containing a symlink is forbidden, as it introduces security risks. An error is returned **at pull** when such a link is detected, as shown in #636.

However, pushing such a symlink works fine. We should add a check to push as well. The behavior of push and pull should be consistent.

**Comment by shizhMSFT** [comment]
Closing this feature request as it conflicts with #644.
