### ISSUE TITLE
Increase code coverage threshold to 75%

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#662]
As we are putting more efforts into the quality of the oras-go library, I suggest increasing threshold of the code coverage of the unit test to `75%` from `70%` and enforce code coverage for PR patches.

https://github.com/oras-project/oras-go/blob/5073458982fd148297c28650b91d879e51ddced1/.github/.codecov.yml#L14-L19

By increasing the code coverage, we aim to make `oras-go` more stable with better quality.

**Comment by khalil-farashiani** [comment]
Hi, could you pls assign this issue to me?
