### ISSUE TITLE
Bug: failed to pull artifacts from harbor because timeout

### ISSUE THREAD

**Issue by zong-zhe** [oras-project/oras-go#717]
I used the example from the official website to upload a txt file to harbor, 

The example i used to push: https://pkg.go.dev/oras.land/oras-go/v2#example-package-PushFilesToRemoteRepository

but when I tried to pull with this example, I got an error

The example i used to pull: https://pkg.go.dev/oras.land/oras-go/v2#example-package-PullFilesFromRemoteRepository

The diagnostic is:

```
Get "http://data-backup-bj.oss-cn-internal.com/docker/registry/v2/blobs/sha256/44/44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a/data": dial tcp 100.118.58.8:80: i/o timeout
```

**Comment by shizhMSFT** [comment]
It seems `data-backup-bj.oss-cn-internal.com` is an internal domain. Can you double confirm your OSS service is accessible from your host?

**Comment by shizhMSFT** [comment]
Closing this issue as it is client network environment configuration error. Please re-open it if more details are provided.
