### ISSUE TITLE
allow an option to allow file store skip copying existed file

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-go#777]
Suppose I am using oras-go to copy an artifact into a file store. The artifact contains several files and the copy process aborted half-way after completed copying the first file. 

In current version (v2.5.0) If I retry copying the artifact, the first file will still be copied again. Need an option to skip the copying if the target file's name and digest both matches.

**Comment by shizhMSFT** [comment]
It looks like we need to add the file to the file store on executing `Exists()`. However, it does not make sense as the `Exists()` should not add the file to the file store even if the file sits on the disk.

**Comment by shizhMSFT** [comment]
If we add the files to the file store in advance, despite the performance issue, the improvement should be done in the CLI.
