### ISSUE TITLE
Trace logs

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#78]
In `v1`, logs are traced via [github.com/sirupsen/logrus](github.com/sirupsen/logrus) as `containerd` uses it.

Since not all adopters use `logrus` or go built-in `log`, we might need something similar to [net/http/httptrace](https://pkg.go.dev/net/http/httptrace).

**Comment by souleb** [comment]
I don't know if that is the intent, but opentelemetry does this (with httptrace), and we could support several sink format (prometheus, oltp).

**Comment by shizhMSFT** [comment]
Closing as log trace can be done at the invoker side using the tool at their choices.
