### ISSUE TITLE
Copy to Azure Container Registry hangs

### ISSUE THREAD

**Issue by trysetnull** [oras-project/oras-go#94]
### Summary
I can use `oras.Copy` to copy from a remote (Azure container registry) to a memory target but not the other way around, the Copy function never returns.

Using the same code works when copying to a remote docker registry (running in a [docker container](https://hub.docker.com/layers/registry/library/registry/2.7/images/sha256-36cb5b157911061fb610d8884dc09e0b0300a767a350563cbfd88b4b85324ce4?context=explore), no authentication and `reg.PlainHTTP = true`).

As a side note, the development environment is running in docker containers via docker compose. 

### Environment
```
go 1.17
replace oras.land/oras-go/v2 => github.com/oras-project/oras-go/v2 v2.0.0-20220105111926-3a35b48527fc
Azure container registry
"type": "Microsoft.ContainerRegistry/registries"
"adminUserEnabled": true

Docker Compose version v2.2.3
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:48 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Steps to reproduce
1. Create an Azure container registry (ACR), e.g. registry.azurecr.io with admin user as owner.
2. Push the hello-world docker container into the registry:
   - docker run -it hello-world
   - docker login registry.azurecr.io
   - docker tag hello-world registry.azurecr.io/hello-world
   - docker push registry.azurecr.io/hello-world
3. Interact with the ACR using the oras-go v2 library; the following is a snippet only with error handling removed:
```go
var credentials = auth.Credential{Username: "<username>", Password: "<pw>"}
reg, _ := remote.NewRegistry("registry.azurecr.io")
reg.RepositoryOptions.Client = &auth.Client{
  Credential: func(c context.Context, s string) (auth.Credential, error) {
    return credentials, nil
  },
}

src, _ := reg.Repository(ctx, "hello-world")

// No problems here, Copy command returns successfully.
dst := memory.New()
oras.Copy(ctx, src, "latest", dst, "")

// Hang happens trying to copy back to the ACR remote.
dst_copy, _ := reg.Repository(ctx, "hello-world-back")
oras.Copy(ctx, dst, "latest", dst_copy, "")
```

`registry.azurecr.io/hello-world:latest` in present in the ACR with the following manifest:
```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 1469,
    "digest": "sha256:feb5d9fea6a5e9606aa995e879d862b825965ba48de054caab5ef356dc6b3412"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 2479,
      "digest": "sha256:2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54"
    }
  ]
}
```

**Comment by shizhMSFT** [comment]
@Wwwsylvia Could you take a look?

**Comment by shizhMSFT** [comment]
Thanks @trysetnull for pointing out the bug. There are actually two bugs:

- #96 
- #97

We will sort out them accordingly.

**Comment by shizhMSFT** [comment]
@trysetnull The bugs have been fixed. Could you have a try on the updated `oras-go` library?

**Comment by trysetnull** [comment]
I can confirm that it now works for me.
