### ISSUE TITLE
Update oras-go to reflect ORAS Artifact Manifest Draft.2

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras-go#95]
Once [Draft.2 of the ORAS Artifact manifest](https://github.com/oras-project/artifacts-spec/milestone/3) is released, implement the changes in oras-go, then [update oras](https://github.com/oras-project/oras/issues/348)

**Comment by sajayantony** [comment]
My feedback here would be to first get notation to use the new libraries and then queue up a short update since this is dependent on having a testable registry server.

**Comment by shizhMSFT** [comment]
I've noticed that the [Manifest Referrers API](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md) has been updated. Once `draft.2` is released, the `oras-go` will be updated accordingly.

**Comment by shizhMSFT** [comment]
Succeeded by #131
